eurekaServerPort: 8761
userServer1Port: 8955
movieServerPort: 8855
zuulServerPort: 8763
zipkinServerPort: 9411
dbPassword: '{cipher}AQBDVZuh2/TxliY4XiwQ7e/Wc0EAucC14ywZShkNjwlNHdgQf/LNAxpF1HcFmmDaUaMgNQHMaKvzgBg7gM5ivF7N+iwsMdi3kPAB7ldr4kAx3LtuDbr9iq46TRobqZVnbiufw9tZdMgVLsH2gQHzG0MXDHUmEBrRrkc+wdnp7xYc3TvE/uSspCfUMIVQ9S7hvXXgEWGCksr5RRNIGyfvODYAyQzCnq5GE3S99WXcoeXl2tLSH5fBZm5xedgaYlGzDtEO796TCmCfH96/8x1ePeQgZiAvfsRtXhPvCGeTTosXWoqEsOSONNaZ6wzBY/kin0WHm3eh9YoAAiMalCQk8p18Yw3WBe5pQsVOE/5Zv6mY7t1Kf5eJWK6sHbWQ3VsK5Gg='



#设置项目ContextPath
server: 
  context-path: /
  tomcat: 
    uri-encoding: UTF-8 #设置Tomcat编码
