spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/springCloudDb?useSSL=false
    username: root
    password: {cipher}AQBDVZuh2/TxliY4XiwQ7e/Wc0EAucC14ywZShkNjwlNHdgQf/LNAxpF1HcFmmDaUaMgNQHMaKvzgBg7gM5ivF7N+iwsMdi3kPAB7ldr4kAx3LtuDbr9iq46TRobqZVnbiufw9tZdMgVLsH2gQHzG0MXDHUmEBrRrkc+wdnp7xYc3TvE/uSspCfUMIVQ9S7hvXXgEWGCksr5RRNIGyfvODYAyQzCnq5GE3S99WXcoeXl2tLSH5fBZm5xedgaYlGzDtEO796TCmCfH96/8x1ePeQgZiAvfsRtXhPvCGeTTosXWoqEsOSONNaZ6wzBY/kin0WHm3eh9YoAAiMalCQk8p18Yw3WBe5pQsVOE/5Zv6mY7t1Kf5eJWK6sHbWQ3VsK5Gg=
    driver-class-name: com.mysql.jdbc.Driver
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
logging:
  level:
    root: INFO
    com.asiainfo.mapper: DEBUG
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 10
